name:                FP2020Khalansky10
version:             0.1.0.0
github:              "FP2020Khalansky/10"
license:             BSD3
author:              "Dmitry Khalansky"
maintainer:          "dkhalansky+fp2020@gmail.com"
copyright:           "2020 Dmitry Khalansky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/FP2020Khalansky/10#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  FP2020Khalansky10-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FP2020Khalansky10
    - HUnit
    - QuickCheck
    - generic-random
    - checkers
